### ISSUE TITLE
Noten transponieren

### ISSUE THREAD

**Issue by mayer-maximilian** [hpi-swa-teaching/MusicNotation#3]
Noten sollen in der internen Datenrepräsentation einfach transponiert werden können. Dies soll auch für ganze Takte oder Parts auf einmal gemacht werden können.

Features:
-  [x] transponieren um eine konkrete Zahl an Halbtonschritten
-  [x] transponieren auf Lied-, Takt- und Noten-Ebene
-  [x] Unit Tests

**Comment by mgjm** [comment]
Closed by #13.
